export const AUTH_ACTIONS = {
  SET_TOKEN: "SET_TOKEN",
  SET_ACCOUNT: "SET_ACCOUNT",
  GET_ACCOUNT_REQUEST: "GET_ACCOUNT_REQUEST",
  GET_ACCOUNT_ERROR: "GET_ACCOUNT_ERROR",
  SET_REDIRECT_TO: "SET_REDIRECT_TO",
};
