export const SUBPLANTYPES_ACTIONS = {
  SET_SUBPLANTYPES: "SET_SUBPLANTYPES",
  ADD_SUBPLANTYPE: "ADD_SUBPLANTYPE",
  EDIT_SUBPLANTYPE: "EDIT_SUBPLANTYPE",
  DELETE_SUBPLANTYPE: "DELETE_SUBPLANTYPE",
};
